### ISSUE TITLE
Error after updating to 6.0.0

### ISSUE THREAD

**Issue by Cherry** [csstools/postcss-preset-env#74]
After updating to 6.0.0, we're seeing errors building all of our CSS files.

```
ERROR in ./apps/instances/modules/minecraft/app.css
Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot read property 'split' of undefined
    at computePolyfillFlagFromStatus (F:\GitHub\website\node_modules\postcss-font-family-system-ui\index.bundle.js:17:33)
    at generatePolyfillFlags (F:\GitHub\website\node_modules\postcss-font-family-system-ui\index.bundle.js:78:32)
    at getSystemUiFamily (F:\GitHub\website\node_modules\postcss-font-family-system-ui\index.bundle.js:104:24)
    at Object.plugin (F:\GitHub\website\node_modules\postcss-font-family-system-ui\index.bundle.js:138:21)
    at promise.then (F:\GitHub\website\node_modules\postcss-preset-env\index.cjs.js:149:97)
    at runLoaders (F:\GitHub\website\node_modules\webpack\lib\NormalModule.js:195:19)
    at F:\GitHub\website\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at F:\GitHub\website\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (F:\GitHub\website\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at F:\GitHub\website\node_modules\happypack\lib\HappyPlugin.js:199:7
    at Object.<anonymous> (F:\GitHub\website\node_modules\happypack\lib\HappyThreadPool.js:85:9)
    at ChildProcess.<anonymous> (F:\GitHub\website\node_modules\happypack\lib\HappyThread.js:86:32)
    at ChildProcess.emit (events.js:182:13)
    at emit (internal/child_process.js:811:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Please advise.

**Comment by jonathantneal** [comment]
I’m sorry so you are having issues. And I’m sorry to say that `postcss-font-family-system-ui` is not one of the plugins I maintain. :( I am investigating this right now.

**Comment by jonathantneal** [comment]
@Cherry, would you mind sharing any options you are passing into the plugin and/or your browserslist?

**Comment by Cherry** [comment]
We're not passing any options into the plugin directly.

Here's our browserslist though:
```
[production]
> 0.5% in my stats
last 3 chrome versions
last 3 edge versions
last 3 firefox versions
firefox esr
last 3 ios versions
last 3 safari versions
not ie <= 11

[development]
last 1 chrome version
last 1 firefox version
last 1 edge version
```
Here's our browserslist-stats.json if needed: https://up.jross.me/5tbex

**Comment by kmvan** [comment]
The same situation with *.scss file.

**Comment by jonathantneal** [comment]
Update: It looks like it is failing here https://github.com/JLHwung/postcss-font-family-system-ui/blob/master/index.js#L14 but I don’t see how it could be failing.

**Comment by jonathantneal** [comment]
@kmvan, @Cherry, any chance you could spin up a tiny repo that reproduces this? Having trouble here. I’m probably missing something stupid. I think we can fix this in minutes once we understand the problem.

**Comment by scriptex** [comment]
Hello, I am having the same issue. You can see the failing branch [here](https://github.com/scriptex/itcss/tree/greenkeeper/postcss-preset-env-6.0.0)

**Comment by jonathantneal** [comment]
Thanks @scriptex, I’ve checked out the greenkeeper branch locally, run `npm install`, and then `npm run build` but it is not failing on my machine.

I also tried running `npx postcss index.css -o main.css -c postcss.config.js`.

And yet, I see the same error very clearly at https://travis-ci.org/scriptex/itcss/builds/431107153#L455

This is confusing.

**Comment by jonathantneal** [comment]
Argh. I think it’s because that plugin tried to implement its own version of browserslist.

**Comment by jonathantneal** [comment]
I hope I’ve patched the issue by replacing the plugin with an internal version for a patch release. Would you please retest in 6.0.1 @Cherry, @scriptex?

**Comment by Cherry** [comment]
6.0.1 appears to work perfectly. Thanks very much @jonathantneal!

**Comment by jonathantneal** [comment]
Wonderful! I’m so happy to read this.

**Comment by kmvan** [comment]
So fast fixed when I woken up.
Thanks your work!

**Comment by scriptex** [comment]
Thanks, @jonathantneal, it is working now!
